### ISSUE TITLE
( BUG Clipboard.ninja Current Version 2.0.7 ) When I open the application, the application crashes

### ISSUE THREAD

**Issue by friendsmobile** [TrafeX/clipboard.ninja-app#1]
# Project Information

* Repository:  https://github.com/TrafeX/clipboard.ninja-app
* Project Name:  Clipboard.ninja
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://play.google.com/store/apps/details?id=nl.trafex.apps.clipboardninja

# Expected behavior

When I try to open the application, the application should not be CRASH, but the application should be open and all options contained in this should be displayed.

# Actual behavior

When I open the application, the application crashes

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=nl.trafex.apps.clipboardninja)the application
*  open the application
* Note the Error

* Browser/App version:  Current Version 2.0.7
* Operating system: 6.0

#### Recording Of The Bug

![20190714_145146](https://user-images.githubusercontent.com/51118734/61182072-1c272f00-a5e3-11e9-93f7-71812f016b67.gif)

#### Logcat

<pre><code>E/AndroidRuntime(11964): FATAL EXCEPTION: create_react_context

E/AndroidRuntime(11964): Process: nl.trafex.apps.clipboardninja, PID: 11964

E/AndroidRuntime(11964): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so

E/AndroidRuntime(11964): 	at com.facebook.soloader.SoLoader.b()

E/AndroidRuntime(11964): 	at com.facebook.soloader.SoLoader.a()

E/AndroidRuntime(11964): 	at com.facebook.soloader.SoLoader.a()

E/AndroidRuntime(11964): 	at com.facebook.soloader.SoLoader.a()

E/AndroidRuntime(11964): 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>()

E/AndroidRuntime(11964): 	at com.facebook.hermes.reactexecutor.a.create()

E/AndroidRuntime(11964): 	at c.a.m.D.run()

E/AndroidRuntime(11964): 	at java.lang.Thread.run(Thread.java:818)
</code></pre>

**Comment by TrafeX** [comment]
Thanks for reporting, this should be fixed in the latest  release (2.0.8)
